'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

upper_limit = 4000000

fibonacci_item0 = 1
fibonacci_item1 = 2
fibonacci_item2 = 3

sum = 2

while fibonacci_item2 <= upper_limit:
    if fibonacci_item2 % 2 == 0:
        sum = sum + fibonacci_item2
    fibonacci_item0 = fibonacci_item1
    fibonacci_item1 = fibonacci_item2
    fibonacci_item2 = fibonacci_item0+ fibonacci_item1
print sum
